# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInsta', '0002_auto_20170802_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsmodel',
            name='caption',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='pointsmodel',
            name='image_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
